
export const saveResource = async (car, user) => {
    const { price, carName, maxPersonQuantity, carIds } = car;
    const body = {
        "contentType": "json",
        "head": {
            "cid": "09031147210876379845",
            "ctok": "",
            "cver": "1.0",
            "lang": "01",
            "sid": "8888",
            "syscode": "09",
            "auth": "",
            "extension": []
        },
        "resourceInfo": {
            "baseInfo": {
                "piCategoryId": 1132,
                // "resourceId": 52878471,
                "name": carName,
                "categoryId": 2,
                "categoryName": "用车",
                "inputLocale": "zh-CN",
                "subName": "",
                "description": price+"",
                "chargeUnit": "辆",
                "visaPeopleGroupType": 0,
                "destinationCity": {
                    "cityId": 41,
                    "cityName": "拉萨",
                    "countryId": 1,
                    "countryName": "中国",
                    "provinceId": 30,
                    "provinceName": "西藏",
                    "eName": "Lhasa",
                    "key": 41,
                    "value": "拉萨"
                },
                "departureCities": [],
                "saleCities": [],
                "departurePlace": "",
                "departureTime": "08:00",
                "zone": [],
                "airportInfo": [],
                "businessType": "OPT",
                "carInfo": {
                    "carMode": 1,
                    "useCarMode": 1
                },
                "trainInfo": {
                    "trainType": 1,
                    "productTrainID": 6166504
                },
                "ticketType": 0,
                "peopleGroup": 1,
                "poiScenicSpot": {},
                "isHighRisk": "F",
                "isHotelResource": "F",
                "isHotelShareRoom": "F",
                "receiveAndSend": {
                    "isNeed": "F",
                    "selectedReceiveAndSend": []
                },
                "isChildNeedExtraPriceForNotShareRoom": "T",
                "isChildAsAdult": "F",
                "maxAdultNum": 1,
                "maxChildNum": 1,
                "isVisaOnTheirOwn": "F",
                "visaInfo": [],
                "isAutoVisa": "F",
                "isAutoGetVisa": "F",
                "expansionCouponId": 0,
                "businessOwner": "VBK",
                "transportation": 0,
                "canCashBack": "F",
                "isVisaAssignInAdvance": "F"
            },
            "bookingControllerInfo": {
                "vendorBookingSeneschalContactId": 0,
                "vendorBookingSeneschalContact": "",
                "vendorBookingSeneschalPhone": "",
                "vendorBookingSeneschalPhoneAreaCode": "",
                "vendorBookingSeneschalEmail": "",
                "vendorBookingContactId": user.contactCardId,
                "isChooseRequired": "T",
                "isDefaultChoose": "T",
                "quantityCalculateMode": "P",
                "minQuantity": 1,
                "maxQuantity": 1,
                "chooseMode": "O",
                "forAdult": "T",
                "forAdultQuantity": 1,
                "forAdultProductQuantity": 1,
                "forChild": "T",
                "forChildQuantity": 1,
                "forChildProductQuantity": 1,
                "minPersonQuantity": 1,
                "maxPersonQuantity": maxPersonQuantity,
                "minTravelDays": 1,
                "maxTravelDays": 999,
                "advanceBookingDays": 1,
                "advanceBookingTime": "20:00",
                "visaAdvanceBookingDayTime": {
                    "visaStuffMakeTime": 0,
                    "visaWaitTime": 0,
                    "visaWorkday": 0,
                    "visaDeliverDay": 0,
                    "visaOrderAndStuff": 0,
                    "visaConfirmDay": 0,
                    "visaAdvanceBookingTime": "20:00",
                    "bookingTimeZoneId": 21
                },
                "isWeekendWork": "F",
                "isHolidayWork": "F",
                "workTemplateId": 1,
                "vendorConfirmModeID": 2,
                "vendorConfirmHours": 0,
                "contact": user.name,
                "vendorBookingPhone": user.mobileNo,
                "msgVenderToConfirmFax": "F",
                "vendorBookingContactPhoneAreaCode": "+86",
                "isChooseDate": "F",
                "departureDays": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7
                ],
                "canFirstDayBooking": "T",
                "canLastDayBooking": "T",
                "isAutoMatch": "F",
                "dPSuitPattern": [
                    1,
                    2,
                    4
                ],
                "active": "T",
                "isShow": "T",
                "customerInfoTemplateID": 0,
                "needCertificate": "F",
                "isSmsNotice": "F",
                "smsInfo": "",
                "bookingTimeZoneId": 21,
                "isSmsVBKNotice": "F",
                "isDefinedPhone": "F",
                "isSmsVBKNoticeType": 1,
                "fillInNumberLimit": "A",
                "piCustomerInfoTemplateId": 29312799,
                "unBookingInfo": {},
                "vendorBookingEmail": user.email,
                "fullVendorBookingPhone": user.mobileNoFull,
                "vendorBookingEmergencyContact": "蒋茂林",
                "vendorComplainContact": "蒋茂林",
                "vendorComplainEMail": "jangmaolin.ai.com@qq.com",
                "vendorComplainContactId": 446454,
                "vendorBookingEmergencyContactId": 446454,
                "providerERAId": null
            },
            "vendorRelatedInfo": {
                "bookingMode": "S",
                "forModifyOrder": "F",
                "canModify": "T",
                "exchangeMode": 1,
                "isProviderDistribution": "F",
                "operationNote": "",
                // TODO 供应商ID
                "vendorId": 1393638,
                "vendorName": "安徽皖美畅行旅行社有限公司",
                "isNeedReceipt": "T",
                "receiptDay": 2,
                "receiptTime": "12:00",
                "receiptContent": "等待地点，司机电话，司机姓名，供应商紧急联系人，供应商紧急电话",
                "pMEID": "PTZC",
                "pAEID": "PTZC",
                "pBMEI": "",
                "regionId": 32,
                "regionName": "代理-运营支持",
                "isClientAssign": "F",
                "productDistributionChannelList": [
                    "bestone",
                    "bestoneb2b",
                    "youtripshop",
                    "ctripshop",
                    "ctrip",
                    "trip",
                    "tripsystem"
                ],
                "deliveryType": 0,
                "deliveryGoodsDescription": ""
            },
            "carIds": carIds
        },
        "customerInfoTemplateOpen": "T"
    }
    const resourceRes = await fetch(
        "https://online.ctrip.com/restapi/soa2/15638/saveResource?_fxpcqlniredt=09031111115146167449&_fxpcqlniredt=09031111115146167449",
        {
            headers: {
                accept: "*/*",
                "accept-language": "zh-CN,zh;q=0.9",
                "content-type": "application/json",
                cookieorigin: "https://vbooking.ctrip.com",
                "sec-ch-ua":
                    '"Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"',
                "sec-ch-ua-mobile": "?0",
                "sec-ch-ua-platform": '"Windows"',
                "sec-fetch-dest": "empty",
                "sec-fetch-mode": "cors",
                "sec-fetch-site": "same-site",
                "x-ctx-locale": "zh-CN",
            },
            referrerPolicy: "no-referrer-when-downgrade",
            body: JSON.stringify(body),
            // `{"contentType":"json","head":{"cid":"09031111115146167449","ctok":"","cver":"1.0","lang":"01","sid":"8888","syscode":"09","auth":"","extension":[]},"resourceInfo":{"baseInfo":{"piCategoryId":1132,"isVisaOnTheirOwn":"F","isHotelResource":"F","inputLocale":"zh-CN","description":"${price}","chargeUnit":"辆","trainInfo":{"trainType":1},"carInfo":{"useCarMode":1,"carMode":1},"ticketType":0,"peopleGroup":1,"canCashBack":"F","isHighRisk":"F","isHotelShareRoom":"F","receiveAndSend":{"isNeed":"F","selectedReceiveAndSend":[]},"isChildAsAdult":"F","maxAdultNum":1,"maxChildNum":1,"isVisaAssignInAdvance":"F","isAutoVisa":"F","isAutoGetVisa":"F","destinationCity":{"cityId":41,"name":"拉萨","eName":"Lhasa","countryId":1,"countryName":"中国","provinceId":30,"provinceName":"西藏","cityCode":"LXA","key":41,"value":"a拉萨/西藏/中国"},"resourceId":null,"categoryId":2,"businessType":"OPT","name":"${carName}"},"bookingControllerInfo":{"vendorConfirmModeID":2,"workTemplateId":1,"vendorBookingContactId":981597,"vendorConfirmHours":0,"isChooseRequired":"T","isDefaultChoose":"T","chooseMode":"O","isChooseDate":"F","canFirstDayBooking":"T","canLastDayBooking":"T","isAutoMatch":"F","active":"T","isShow":"T","isSmsNotice":"F","isSmsVBKNoticeType":1,"forAdult":"T","forAdultQuantity":1,"forAdultProductQuantity":1,"forChild":"T","forChildQuantity":1,"forChildProductQuantity":1,"advanceBookingDays":1,"advanceBookingTime":"20:00","bookingTimeZoneId":21,"minPersonQuantity":1,"maxPersonQuantity":${maxPersonQuantity},"minTravelDays":1,"maxTravelDays":999,"maxQuantity":1,"minQuantity":1,"visaAdvanceBookingDayTime":{"visaStuffMakeTime":0,"visaWaitTime":0,"visaWorkday":0,"visaDeliverDay":0,"visaOrderAndStuff":0,"visaConfirmDay":0,"visaAdvanceBookingTime":"12:00","bookingTimeZoneId":21},"providerERAId":null,"contact":"安思科","vendorBookingEmail":"ansike@qq.com","vendorBookingContactPhoneAreaCode":"+86","vendorBookingPhone":"15910250965","fullVendorBookingPhone":"+86 15910250965","piCustomerInfoTemplateId":29312799},"vendorRelatedInfo":{"bookingMode":"S","forModifyOrder":"F","canModify":"T","exchangeMode":1,"isProviderDistribution":"F","isNeedReceipt":"T","receiptDay":2,"receiptTime":"12:00","receiptContent":"等待地点，司机电话，司机姓名，供应商紧急联系人，供应商紧急电话","pMEID":"PTZC","pAEID":"PTZC","regionId":32,"isClientAssign":"F","productDistributionChannelList":["bestone","bestoneb2b","youtripshop","ctripshop","online","ctrip","trip","tripsystem"]},"carIds":[1,2,3]},"customerInfoTemplateOpen":"T"}`,
           
            method: "POST",
            mode: "cors",
            credentials: "include",
        }
    );
    return await resourceRes.json();
}
